site_name: 性界大战 官方WIKI
site_description: 《性界大战》官方资料站
repo_name: spj
repo_url: https://github.com/mitaofaxingwiki/spj

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: deep purple
      accent: pink
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

nav:
  - 首页: index.md
  - 世界观: world.md
  - 新手手册: beginner.md
